-- public.auth_user definition
-- Drop table
-- DROP TABLE public.auth_user;
CREATE TABLE public.auth_user (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE),
	"password" varchar(128) NOT NULL,
	last_login timestamptz NULL,
	is_superuser bool NOT NULL,
	username varchar(150) NOT NULL,
	first_name varchar(150) NOT NULL,
	last_name varchar(150) NOT NULL,
	email varchar(254) NOT NULL,
	is_staff bool NOT NULL,
	is_active bool NOT NULL,
	date_joined timestamptz NOT NULL,
	CONSTRAINT auth_user_pkey PRIMARY KEY (id),
	CONSTRAINT auth_user_username_key UNIQUE (username)
);
CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);

-- public.auth_group definition
-- Drop table
-- DROP TABLE public.auth_group;
CREATE TABLE public.auth_group (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE),
	"name" varchar(150) NOT NULL,
	CONSTRAINT auth_group_name_key UNIQUE (name),
	CONSTRAINT auth_group_pkey PRIMARY KEY (id)
);
CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);

-- public.auth_user_groups definition
-- Drop table
-- DROP TABLE public.auth_user_groups;
CREATE TABLE public.auth_user_groups (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE),
	user_id int4 NOT NULL,
	group_id int4 NOT NULL,
	CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id),
	CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id),
	CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED,
	CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);
CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);

CREATE TABLE public.tarefa (
	codigo int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE),
	tipo varchar(150) NOT NULL,
	assunto varchar(150) NOT NULL,
	descricao varchar(500) NOT NULL,
	data_tarefa timestamptz NULL,	
	ticket int2 NOT NULL,
	horas int2 NOT null,
	user_id int4 NOT null,
	CONSTRAINT tarefas_pkey PRIMARY KEY (codigo),
	CONSTRAINT tarefa_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.auth_user(id)
);

alter table public.auth_user add CONSTRAINT auth_user_email_key UNIQUE (email);

alter table public.tarefa add column codigo_pai int null;

--inserts
INSERT INTO public.auth_user
(id, "password", last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined)
VALUES(1, '123456', '2023-10-16 15:10:10.000', true, 'admin', 'admin', 'admin', 'admin@gmail.com', false, true, '2023-10-16 15:10:10.000');
INSERT INTO public.auth_user
(id, "password", last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined)
VALUES(2, '123456', '2023-10-16 15:10:10.000', true, 'geo', 'geo', 'geo', 'geo@gmail.com', false, true, '2023-10-16 15:10:10.000');
INSERT INTO public.auth_user
(id, "password", last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined)
VALUES(3, '123456', '2023-10-16 15:10:10.000', true, 'jessica', 'jessica', 'jessica', 'jessica@gmail.com', false, true, '2023-10-16 15:10:10.000');
INSERT INTO public.auth_user
(id, "password", last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined)
VALUES(4, '123456', '2023-10-16 15:10:10.000', true, 'leonardo', 'leonardo', 'leonardo', 'leonardo@gmail.com', false, true, '2023-10-16 15:10:10.000');

